language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules
script:
  - yarn
  - yarn run coveralls
services:
  - postgresql
before_script:
  - psql -c 'create database mindtest;' -U postgres
